### ISSUE TITLE
Unable to create a WSClient which times out before the request_timeout duration spans

### ISSUE THREAD

**Issue by kebab-mai-haddi** [paritytech/jsonrpsee#613]
I want to create a `WSClient` from `jsonrpeesee` so that I can use it in [subxt's](https://github.com/paritytech/subxt/) `ClientBuilder`. I face an error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Transport(Error when opening the TCP socket: Operation timed out (os error 60))', src/main.rs:21:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

In my code, I set the timeout to be 10 minutes but the error is thrown in 3-4 minutes.

My code is:
```
use jsonrpsee_ws_client::WsClientBuilder;
use std::time::Duration;
use subxt::ClientBuilder;

#[subxt::subxt(runtime_metadata_path = "polkadot_metadata.scale")]
pub mod polkadot {}

#[async_std::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    env_logger::init();
    // let connection_timeout_secs = Duration::new(secs: 60, nanos: 0);
    let connection_timeout_duration = Duration::new(600, 0);

    let url = "wss://moonriver.api.onfinality.io:9944/public-ws";

    let client = WsClientBuilder::default()
        .connection_timeout(connection_timeout_duration)
        .request_timeout(connection_timeout_duration)
        .build(url)
        .await
        .unwrap();

    println!("Client established: {:?}", client);

    // let api = ClientBuilder::new()
    //     .set_client(client)
    //     .set_url(url)
    //     .build()
    //     .await?
    //     .to_runtime_api::<polkadot::RuntimeApi<polkadot::DefaultConfig>>();

    // let mut iter = api.storage().system().account_iter(None).await?;

    // while let Some((key, account)) = iter.next().await? {
    //     println!("{}: {}", hex::encode(key), account.data.free);
    // }
    Ok(())
}

```

I tried using `ok()` instead of `unwrap()` while calling `WsClientBuilder::default` but that makes the `client` variable unusable in the commented lines later on: `let api = ClientBuilder::new().set_client(client)`. I then get the error: `^^^^^^ the trait `From<std::option::Option<WsClient>>` is not implemented for `RpcClient``.

The standard example for WSClientBuilder shows `unwrap` and tbh, I am okay with using unwrap. 

How do I create a client with my specified timeouts, and successfully?

**Comment by niklasad1** [comment]
Hey @kebab-mai-haddi 

That's an OS error on the socket (not the request or connection timeouts in jsonrpsee), we using are https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.connect for this..

I guess we would need to set the `keepalive` on the TcpSocket doesn't look to be possible.

**Comment by niklasad1** [comment]
Can you run your example with `RUST_LOG="trace"` and provide the logs please?

**Comment by kebab-mai-haddi** [comment]
[2021-12-15T10:17:23Z TRACE async_io::driver] block_on: sleep until notification
[2021-12-15T10:17:23Z TRACE async_io::driver] block_on: sleep until notification
[2021-12-15T10:17:23Z TRACE async_io::driver] main_loop: sleeping for 50 us
[2021-12-15T10:17:23Z TRACE async_io::driver] main_loop: notified
[2021-12-15T10:17:23Z TRACE async_io::driver] block_on: waiting on I/O
[2021-12-15T10:17:23Z TRACE async_io::driver] block_on: sleep until notification
[2021-12-15T10:17:23Z TRACE async_io::reactor] process_timers: 0 ready wakers
[2021-12-15T10:17:23Z TRACE polling] Poller::wait(_, None)
[2021-12-15T10:17:23Z TRACE async_io::driver] main_loop: sleeping for 50 us
[2021-12-15T10:17:23Z TRACE polling::kqueue] wait: kqueue_fd=6, timeout=None
[2021-12-15T10:17:23Z TRACE async_io::driver] main_loop: sleeping for 75 us
[2021-12-15T10:17:23Z TRACE async_io::driver] main_loop: sleeping for 100 us
[2021-12-15T10:17:23Z TRACE async_io::driver] main_loop: sleeping for 250 us
[2021-12-15T10:17:23Z TRACE async_io::driver] main_loop: sleeping for 500 us
[2021-12-15T10:17:23Z TRACE async_io::driver] main_loop: sleeping for 750 us
[2021-12-15T10:17:23Z TRACE async_io::driver] main_loop: sleeping for 1000 us
[2021-12-15T10:17:23Z TRACE async_io::driver] main_loop: sleeping for 2500 us
[2021-12-15T10:17:23Z TRACE async_io::driver] main_loop: sleeping for 5000 us
[2021-12-15T10:17:23Z TRACE async_io::driver] main_loop: sleeping for 10000 us
[2021-12-15T10:17:24Z TRACE mio::poll] registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
[2021-12-15T10:17:24Z TRACE async_io::driver] block_on: sleep until notification
[2021-12-15T10:18:39Z TRACE mio::poll] deregistering event source from poller
[2021-12-15T10:18:39Z TRACE mio::poll] registering event source with poller: token=Token(16777216), interests=READABLE | WRITABLE
[2021-12-15T10:18:39Z TRACE async_io::driver] block_on: sleep until notification
[2021-12-15T10:19:54Z TRACE mio::poll] deregistering event source from poller
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Transport(Error when opening the TCP socket: Operation timed out (os error 60))', src/main.rs:20:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by niklasad1** [comment]
@kebab-mai-haddi 

I could re-produce this myself at least the connection timeout but I think that you are just using the wrong port, you should use `wss://moonriver.api.onfinality.io:443/public-ws` i.e, `443` for TLS.

**Comment by kebab-mai-haddi** [comment]
Even though you provided the right port, you were getting the error?

**Comment by kebab-mai-haddi** [comment]
Also, how were you able to deduce whether you needed 443 port - want to know why did I not catch it.

**Comment by niklasad1** [comment]
Hey again,

It works fine on port `443` for me but port `9944` doesn't work.
It's because `443` is the default port for TLS/SSL sometimes hard to catch... :)
