### ISSUE TITLE
[benchmarks] Panic while running benchmarks

### ISSUE THREAD

**Issue by lexnv** [paritytech/jsonrpsee#685]
### Details
- `cargo bench -p jsonrpsee-benchmarks -- --output-format bencher` results in a repeating panic
- commit: `2864756 - dependabot[bot] - chore(deps): update parking_lot requirement from 0.11 to 0.12 (#682)`
- os | hardware: `macOS Monterey v12.2` | apple M1 pro

### Panic Details

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Transport(Error while performing the HTTP request)', benches/bench.rs:286:107
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: tokio::runtime::task::core::CoreStage<T>::poll
   5: tokio::runtime::task::harness::Harness<T,S>::poll
   6: std::thread::local::LocalKey<T>::with
   7: tokio::runtime::thread_pool::worker::Context::run_task
   8: tokio::runtime::thread_pool::worker::Context::run
   9: tokio::macros::scoped_tls::ScopedKey<T>::set
  10: tokio::runtime::thread_pool::worker::run
  11: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  12: tokio::runtime::task::harness::Harness<T,S>::poll
  13: tokio::runtime::blocking::pool::Inner::run
```

**Comment by dvdplm** [comment]
> * `cargo bench -p jsonrpsee-benchmarks -- --output-format bencher` results in a repeating panic

Is it the use of `--output-format` that triggers the panic?

**Comment by niklasad1** [comment]
nah, it most likely [this](https://github.com/paritytech/jsonrpsee/blob/master/benches/bench.rs#L279) that opens too many connections

similar to what you experienced before @dvdplm with your `ulimit attempts` on `macOS`

@lexnv 

perhaps you could try modify the number of connections and report back if you still get the same panic

**Comment by dvdplm** [comment]
Not so sure this one's the same tbf. The actual error is this: `hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 49, kind: AddrNotAvailable, message: "Can't assign requested address" }))'`. It comes from [here](https://github.com/paritytech/jsonrpsee/blob/1e00d8b2331bf34b46c704577505b0c4781f59eb/client/http-client/src/transport.rs#L104).

@lexnv to increase the resource limit on Monterey this seems to work alright:

```
sudo launchctl limit maxfiles 9000000 9999999
ulimit -Sn 9000000
```

**Comment by niklasad1** [comment]
ah ok, that's weird that's something else for sure maybe it is https://github.com/hyperium/hyper/issues/1757 then.

**Comment by dvdplm** [comment]
Yeah I was thinking the same. Do we set `SO_REUSEADDR` somewhere? (And is that a thing on macOS?)

**Comment by niklasad1** [comment]
No, at least not the client `HttpConnector` https://docs.rs/hyper/latest/src/hyper/client/connect/http.rs.html#120 that is used by the benches.

I think the `HttpsConnector` is using that under the hood too.

but for the server we actually set [SO_REUSEADDR](https://github.com/paritytech/jsonrpsee/blob/master/http-server/src/server.rs#L210)

**Comment by niklasad1** [comment]
Ok, we could actually try to set  `SO_REUSEADDR == true` in the client too then.

**Comment by lexnv** [comment]
This might be related to ephemeral port exhaustion.

### Default settings
```
$ sysctl net.inet.ip.portrange.first net.inet.ip.portrange.last
net.inet.ip.portrange.first: 49152
net.inet.ip.portrange.last: 65535
```

`watch -c 'netstat -an | grep 127.0.0.1 | wc -l' ` during benchmark would hit around 16360.

### Modified settings

```
$ sysctl net.inet.ip.portrange.first net.inet.ip.portrange.last
net.inet.ip.portrange.first: 49152
net.inet.ip.portrange.last: 65535
```

`watch -c 'netstat -an | grep 127.0.0.1 | wc -l' ` during benchmark would hit around 32731.

Might be worth trying to set `IP_BIND_ADDRESS_NO_PORT` on the socket.

**Comment by niklasad1** [comment]
cool got it, [or temporary reduce this to 8 or something](https://github.com/paritytech/jsonrpsee/blob/master/benches/bench.rs#L279)

On the `http client` it's not possible to configure that on the socket but should be possible on the `http server` because we configure to socket ourselves there but not sure if that would help in the benches should only be one server per benchmark anyways.

**Comment by dvdplm** [comment]
> cool got it, [or temporary reduce this to 8 or something](https://github.com/paritytech/jsonrpsee/blob/master/benches/bench.rs#L279)

I have it set to `2` and it still crashes. Using @lexnv 's `netstat` command and ephemeral port tweaks I see that it starts crashing somewhere between 25k-40k connections. Peak values are ~48k here.

**Comment by niklasad1** [comment]
This could also be related to that `backlog` is a completely different story on BSD/macOS than on Linux and you might reach that limit.

As a way to test this hypothesis either increase the backlog [here](https://github.com/paritytech/jsonrpsee/blob/master/http-server/src/server.rs#L226) or try [hyper's API `sleep_on_accept_errors](https://docs.rs/hyper/0.14.18/hyper/server/struct.Builder.html#method.tcp_sleep_on_accept_errors) [here](https://github.com/paritytech/jsonrpsee/blob/master/http-server/src/server.rs#L229)
